# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ToHey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToHey
  pod 'AlertToast'

  target 'ToHeyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToHeyUITests' do
    # Pods for testing
  end

end
